# site settings
title: Forty
subtitle: by HTML5 UP
email: youremailaddress@gmail.com
description: A responsive site template designed by HTML5 UP! and released under the Creative Commons.
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
linkedin_url:
gitlab_url:
github_url:
facebook_url:
twitter_url:
instagram_url:
pinterest_url:
slack_url:
telegram_url:

# build settings
markdown: kramdown
sass:
  style: compressed

# GitHub Pages default build settings
# lsi: false
# safe: true
# incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
